# Generated by Django 5.0.6 on 2024-06-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=25)),
                ('surname', models.CharField(blank=True, max_length=20)),
                ('isfree', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
                ('price', models.IntegerField(blank=True)),
                ('weight', models.IntegerField(blank=True)),
                ('preview_picture', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(blank=True)),
                ('delivery_address', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
