# Generated by Django 5.0.6 on 2024-06-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermachine',
            name='content',
            field=models.ManyToManyField(blank=True, null=True, related_name='orders', to='testapp1.mealmachine'),
        ),
    ]
